### ISSUE TITLE
connectToAvailableSSID() is not working

### ISSUE THREAD

**Issue by cajay01** [nishkarsh/android-wificonnect#1]
```
WifiConnectionManager.connectToAvailableSSID(routerSSID,  ConnectionStateChangedListener listener);
```

not able to how to implement ConnectionStateChangedListener it is giving error can not be resolved to variable

**Comment by nishkarsh** [comment]
@cajay01 `ConnectionStateChangedListener` is an interface that belongs to `WifiConnectionManager` class. You may refer it using `WifiConnectionManager.ConnectionStateChangedListener`

**Comment by cajay01** [comment]
hey nishkarsh I am doing btach connection with wifi routers so I have to connect multiple routers one after another ,when I switch from one router to other I want to implement this bound procedure but I am not able to get it. Can you share how to do it ?
